### ISSUE TITLE
Uncaught ReferenceError: regsiteredAtomCommands is not defined

### ISSUE THREAD

**Issue by lemongrassnginger** [dqsully/dqs-shell-commands#3]
Could be linked to #2 

[Enter steps to reproduce:]

1. Removed a project folder using treeview context menu > Remove project folder
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [dqs-shell-commands](https://github.com/dqsully/dqs-shell-commands) package 2.1.1

### Stack Trace

Uncaught ReferenceError: regsiteredAtomCommands is not defined

```
At C:\Users\sbell\.atom\packages\dqs-shell-commands\lib\dqs-shell-commands.js:169

ReferenceError: regsiteredAtomCommands is not defined
    at commands.refreshPaths (/packages/dqs-shell-commands/lib/dqs-shell-commands.js:169:17)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Project.module.exports.Project.removePath (/app.asar/src/project.js:314:22)
    at TreeView.module.exports.TreeView.removeProjectFolder (/app.asar/node_modules/tree-view/lib/tree-view.js:1204:31)
    at /app.asar/node_modules/tree-view/lib/tree-view.js:352:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1168:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:23.5.0 core:backspace (input.hidden-input)
     -0:22.6.0 project-manager:list-projects (input.hidden-input)
     -0:19.9.0 editor:delete-to-beginning-of-word (input.hidden-input)
  2x -0:19.4.0 core:backspace (input.hidden-input)
     -0:18.8.0 editor:consolidate-selections (input.hidden-input)
     -0:18.8.0 dqs-shell-commands-config:hide (input.hidden-input)
     -0:18.8.0 core:cancel (input.hidden-input)
     -0:14.2.0 tree-view:remove-project-folder (span.name.icon.icon-repo)
```

### Non-Core Packages

```
atom-alignment 0.12.1 
atom-html-preview 0.1.22 
atom-keyboard-macros-vim 0.1.6 
atom-shell-commands 1.5.0 
atom-terminal 0.8.0 
atom-ternjs 0.16.1 
atomic-chrome 0.3.0 
calc 0.4.0 
character-table 0.4.3 
column-select 0.2.0 
ctrl-dir-scroll 0.2.2 
date 1.1.1 
docblockr 0.9.1 
docs undefined 
dqs-shell-commands 2.1.1 
duplicate-removal 0.1.3 
git-log 0.4.1 
git-plus 7.1.0 
json-converter 0.2.4 
language-abap 1.1.0 
language-diff 0.7.0 
language-latex 1.0.0 
language-mediawiki 2.2.0 
language-vbscript 0.7.0 
last-cursor-position 0.9.0 
linter 1.11.21 
linter-coffeelint 1.2.1 
linter-eslint 8.0.0 
linter-jsonlint 1.3.0 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.0 
markdown-writer 2.6.3 
merge-conflicts 1.4.4 
pdf-view 0.54.0 
project-manager 3.3.3 
simple-panes 1.1.0 
sort-lines 0.14.0 
sorter 0.1.2 
split-diff 1.1.1 
symbol-gen 1.3.1 
tablr 1.8.1 
tabs-to-spaces 1.0.3 
terminal-status 1.6.8 
vim-mode 0.66.0 
vim-mode-plus 0.82.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
vim-surround 0.8.1 
```

**Comment by dqsully** [comment]
Thanks, it was a typo. A fix will be up soon

**Comment by dqsully** [comment]
Fix is up; I am closing this.

**Comment by lemongrassnginger** [comment]
yep, seems fine now :)
